package ua.edu.znu.cs.controllers;

import java.util.concurrent.atomic.AtomicLong;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import ua.edu.znu.cs.entities.TermsUser;
import ua.edu.znu.cs.models.TermsUserRepository;



@RestController
@RequestMapping("/term-user")
public class TermsUserController {
    
    @Autowired  // This means to get the bean called userRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private TermsUserRepository termsUserRepository;


    /**
     * GET http://localhost:8080/term-user/all
     */

    @GetMapping(path="/all")
    public @ResponseBody Iterable<TermsUser> getAllUsers() {
        // This returns a JSON or XML with the users
        return termsUserRepository.findAll();
    }
}